version: '3.9'
services:
  selenoid:
    image: aerokube/selenoid:latest-release
    network_mode: bridge
    ports:
      - "4444:4444"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./config/browsers.json:/etc/selenoid/browsers.json"
      - "./videos:/opt/selenoid/video"
      - "./logs:/opt/selenoid/logs"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=/opt/selenoid/video
      - ENABLE_VIDEO=true

  selenoid-ui:
    image: aerokube/selenoid-ui:latest-release
    network_mode: bridge
    ports:
      - "8080:8080"
    links:
      - selenoid
    environment:
      - SELENOID_URI=http://selenoid:4444
