version: '3.9'
services:
  selenoid:
    image: aerokube/selenoid:latest-release
    platform: linux/amd64
    volumes:
      - ./config:/etc/selenoid
      - ./videos:/opt/selenoid/video
    ports:
      - 4444:4444
    restart: unless-stopped

  selenoid-ui:
    image: aerokube/selenoid-ui:latest-release
    depends_on: [selenoid]
    ports:
      - 8080:8080
    environment:
      SELENOID_URI: http://selenoid:4444
    restart: unless-stopped

  allure:
    image: frankescobar/allure-docker-service:latest
    volumes:
      - ./allure-results:/app/allure-results
    ports:
      - 5050:5050
    restart: unless-stopped
