name: WebdriverIO CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        attempt: [1, 2, 3]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: sudo apt-get install -y docker-compose

      - name: Install Dependencies
        run: npm install

      - name: Create Allure Results Directory
        run: mkdir -p allure-results

      - name: Start Required Services
        run: docker-compose up -d

      - name: Health Check - Services
        run: |
          curl --retry 5 --retry-delay 5 -s http://localhost:4444/status
          curl --retry 5 --retry-delay 5 -s http://localhost:8080

      - name: Run WebdriverIO Tests
        env:
          WEB_URL: ${{ secrets.WEB_URL }}
          WEB_USERNAME: ${{ secrets.WEB_USERNAME }}
          WEB_PASSWORD: ${{ secrets.WEB_PASSWORD }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: npm run dock

      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results/

      - name: Slack Notification
        if: always()
        run: node ./config/waitForAllure.js
